language: php

addons:
  code_climate:
    repo_token: 6e55e1aeb6f83b6954a22c5a20e9ffbc88343e6ed77e22870d746f702608501e

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_install:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: 
     - mkdir -p build/logs
     - bin/phpunit -c phpunit.metrics.xml.dist

after_script:
    - bin/test-reporter
